{{- if .Values.ingressroute.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
spec:
  entryPoints:
    - {{ .Values.ingressroute.entry_point }}
  routes:
  - match: Host(`{{ .Values.ingressroute.host }}`)
    kind: Rule
    services:
    - name: {{ .Values.ingressroute.service.name }}
      port: {{ .Values.ingressroute.service.internalPort }}
  tls:
  {{- if .Values.ingressroute.tls_secret_name }}
    secretName: {{ .Values.ingress.traefik.tls_secret_name }}
  {{- else }}
    certResolver: default
  {{- end }}
{{- end }}