apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  dbuser: {{ .Values.dbuser | b64enc }}
  dbpwd:  {{ .Values.dbpwd | b64enc }}
  dbhost: {{ .Values.dbhost | b64enc }}
  dbname: {{ .Values.dbname | b64enc }}
  dbport: {{ .Values.dbport | b64enc }}
  svport: {{ .Values.svport | b64enc }}
