{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "bke-app.fullname" . }}
  labels:
    {{- include "bke-app.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "bke-app.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - resource:
        name: cpu
        target:
          averageValue: {{ print ( mul (trimSuffix "m" .Values.resources.requests.cpu) 3 ) "m" }}
          type: AverageValue
      type: Resource
    {{- end }}
    {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - resource:
        name: memory
        target:
          averageValue: {{ print ( mul (trimSuffix "Mi" .Values.resources.requests.memory) 3 ) "Mi" }}
          type: AverageValue
      type: Resource
    {{- end }}
{{- end }}
