{{- if .Values.ingressroute.enabled }}
{{- $fullName := include "bke-app.fullname" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata: 
  name: {{ $fullName }}
spec:
  entryPoints:
  - {{ .Values.ingressroute.entry_point }}
  routes:  
  - kind: Rule
    match: Host(`{{ .Values.ingressroute.host }}` && PathPrefix(`{{ .Values.ingressroute.pathPrefix }}`) 
    {{- if .Values.ingressroute.middleware.enabled }}
    middlewares:
    - name: strip-prefix
{{- end }}
    priority: {{ .Values.ingressroute.priority }}
    services:
    - name: {{ .Values.ingressroute.service.name }}
      port: {{ .Values.ingressroute.service.internalPort }}
{{- end }}