apiVersion: v1
kind: Service
metadata:
  name: {{ include "bke-app.fullname" . }}
  labels:
    {{- include "bke-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      nodePort: {{ .Values.service.nodeport }}
  selector:
    {{- include "bke-app.selectorLabels" . | nindent 4 }}
